name: Retail Lakehouse Platform CI

on:
  push:
    branches: [ main, master, Aneesh ]
  pull_request:
    branches: [ main, master, Aneesh ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      env:
        SOURCE_DATABASE_URL: sqlite:///test_source.db
        DATABASE_URL: sqlite:///test_warehouse.db
        FALLBACK_DB_PATH: ./retail_fallback.db
      run: |
        python -m pytest tests/
